database/migrations/Version20220531175731.php
public/assets/css/auth/consent.css

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2633725&fileview=grid

Consent page UI tweaks & scope descriptions fixes

---

app/Http/Controllers/Auth/RegisterController.php
public/assets/js/admin/edit-user.js
public/assets/js/admin/users.js
public/assets/js/jquery.validate.additional.custom.methods.js
public/assets/js/profile.js

Signed-off-by: smarcet@gmail.com <smarcet@gmail.com>
Change-Id: I88d95e23256fadf5780ca7a8a56a518096dfabb2

punny code fixes

---

app/Validators/CustomValidator.php

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3143202&fileview=grid

Email validation fix

---

resources/js/oauth2/consent.module.scss

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3081181&fileview=grid

Fix word wrapping on large urls

---

app/Http/Controllers/Api/UserActionApiController.php
resources/js/admin/edit_user/actions.js
resources/js/components/user_actions_grid.js
resources/js/profile/actions.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3066314&fileview=grid

User actions grid tweaks

---

public/assets/css/private-keys.css
public/assets/js/oauth2/profile/admin/server-private-keys.js
resources/views/oauth2/profile/admin/server-private-key-add-form.blade.php

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3254952&stafilter=NotComplete&fileview=grid

datepicker setup and css fixes

---

resources/js/email_verification/email_verification.js
resources/js/forgot_password/forgot_password.js
resources/js/home/home.js
resources/js/login/login.js
resources/js/reset_password/reset_password.js
resources/js/set_password/set_password.js
resources/js/signup/signup.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3287065&stafilter=NotComplete&fileview=grid

update creteMuiTheme occurrences

---

app/libs/Auth/Models/User.php
database/migrations/Version20230601162315.php

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2901244&stafilter=NotComplete&fileview=grid

default db field values

---

app/Http/Controllers/UserController.php
app/libs/Auth/AuthService.php
resources/js/components/user_actions_grid.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3365689&stafilter=NotComplete&fileview=grid

move logout event to service

---

resources/js/oauth2/profile/clients/components/new_client_dialog.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3366367&stafilter=NotComplete&fileview=grid

fix new client creation feedback dialog

---

app/Mail/OAuth2PasswordlessOTPMail.php
resources/views/emails/oauth2_passwordless_otp.blade.php

https://tipit.avaza.com/project/view/347915#view-3

change email verbiage

---

resources/js/login/login.js
resources/js/utils.js

https://tipit.avaza.com/project/view/347915#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3408514&stafilter=NotComplete&fileview=grid

Registration: change login verbiage

---

resources/js/login/login.js

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3464585&stafilter=NotComplete&fileview=grid
Signed-off-by: romanetar [roman_ag@hotmail.com]

text tweaks

---

app/Http/Controllers/UserController.php
app/Strategies/DefaultLoginStrategy.php
resources/js/login/login.js

Change-Id: I0ced95dda289e4d246d786fa7b39849aeebcb594

fix: double click bug on login forms

---

public/assets/js/admin/edit-group.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3535757&stafilter=NotComplete&fileview=grid

fix: encode users query in group users typeahead

---

resources/js/oauth2/profile/clients/actions.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3419617&stafilter=NotComplete&fileview=grid

paging size adjustment

---

resources/js/admin/edit_user/edit_user.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3614203&stafilter=NotComplete&fileview=grid

feat: add permission checkboxes to user edition page

---

app/libs/Auth/Models/User.php
public/assets/js/ajax.utils.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3535757&stafilter=NotComplete&fileview=grid
Signed-off-by: romanetar [roman_ag@hotmail.com]

fix: show meaningful message when user already belonged to group

---

resources/js/oauth2/profile/edit_client/components/oauth_panel.js

ref https://tipit.avaza.com/project/view/360253#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3642027&stafilter=NotComplete&fileview=grid

fix: tooltip render error when no content

---

app/Providers/AppServiceProvider.php
public/assets/js/ajax.utils.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3690782&stafilter=NotComplete&fileview=grid

fix: password policy validation

---

resources/js/oauth2/profile/edit_client/actions.js
resources/views/oauth2/profile/edit-client.blade.php

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3774311&stafilter=NotComplete&fileview=grid

fix: validation based on app type

---

resources/js/oauth2/profile/edit_client/components/oauth_panel.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3737580&stafilter=NotComplete&fileview=grid

fix: make optional fields nullable

---

app/Mail/OAuth2PasswordlessOTPMail.php

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3784772&stafilter=NotComplete&fileview=grid

feat: add otp code in the otp email subject
